export const supportedUserRoles = [
  "DOCTOR",
  "ADMIN",
  "RECEPTIONIST",
  "PHARMACIST",
  "INVENTORY_MANAGER",
  "CO_ADMIN",
  "OTHER",
];

export const permissions = [
  "ADMIN",
  "DOCTOR_APPOINTMENTS",
  "DOCTOR_PRESCRIBE_MEDICINE",
  "PHARMACY_PRESCRIPTIONS",
  "PHARMACY_RECEIPT",
  "RECEPTION_ADD_APPOINTMENT",
  "RECEPTION_CREATE_PATIENT",
  "INVENTORY_VIEW",
  "INVENTORY_ADD_MEDICINE",
];
