export const defaultConfig = {
  app_logo: '/images/logo.jpg',
  app_light_color: '#F9F9FB',
  app_dark_color: '#484C56',
  app_theme_color: '#00BDC1',
  app_name: 'Dr. M.A. Ansari Health Centre',
  footer_text: 'Project Designed and Developed in-house under Dept. of CSE (FET-JMI)',
  footer_link_text: 'Know More . . .',
  homepage_contents: {
    people: [
      {
        name: 'Mukhtar Ahmed Ansari',
        image:
          'https://upload.wikimedia.org/wikipedia/commons/0/0e/Mukhtar_Ahmed_Ansari_1980_stamp_of_India.jpg',
        description:
          'Mukhtar Ahmed Ansari (25 December 1880 - 10 May 1936) was an Indian nationalist and political leader, and former president of the Indian National Congress and the Muslim League during the Indian Independence Movement. One of the founders of the Jamia Millia Islamia University he remained its chancellor 1928 to 1936.',
      },
    ],
    carousel: [
      '/images/center.jpg',
      '/images/center.jpg',
      '/images/center.jpg',
      '/images/center.jpg',
    ],
  },
  sidebar_keymaps: {
    home: 'Home',
    receptionists: 'Receptionists',
    doctors: 'Doctors',
    pharmacists: 'Pharmacists',
    inventory_managers: 'Inventory Managers',
    co_admins: 'Co Admins',
    others: 'Others',
    patients: 'Patients',
    log_reports: 'Log Reports',
    dev_config: 'Dev Config',
    create_appointment: 'Create Appointment',
    doctor_appointments: 'Doctor Appointments',
    prescribe_medicines: 'Prescribe Medicines',
    patient: 'Patient',
    pharmacy: 'Pharmacy',
    create_receipts: 'Create Receipts',
    create_patient: 'Create Patient',
    add_to_inventory: 'Add To Inventory',
    view_medicines: 'View Medicines',
    view_non_medicines: 'View Non Medicines',
    view_other_assets: 'View Other Assets',
    documentation: 'Documentation',
    about: 'About',
  },
  developers: [
    {
      name: 'MD Rashid Hussain',
      image: '/images/rashid.jpg',
      department: 'Dept. of CSE, FET-JMI',
      batch: '2020-2024',
      github: 'https://github.com/m3rashid',
      linkedin: 'https://linkedin.com/in/m3rashid',
      portfolio: 'https://m3rashid.in',
    },
    {
      name: 'Mohammad Sarfraz Alam',
      image: '/images/sarfraz.jfif',
      department: 'Dept. of ECE, FET-JMI',
      batch: '2020-2024',
      github: 'https://github.com/Sarfraz-droid',
      linkedin: 'https://www.linkedin.com/in/sarfraz-alam-113575201/',
      portfolio: 'https://sarfraz-alam.netlify.app/',
    },
    {
      name: 'Husain Shahid Rao',
      image: '/images/husain.jfif',
      department: 'Dept. of CSE, FET-JMI',
      batch: '2020-2024',
      github: 'https://github.com/husain3012',
      linkedin: 'https://github.com/husain3012',
      portfolio: 'https://husain3012.github.io/mysite/',
    },
    {
      name: 'Anzal Husain Abidi',
      image: 'images/anzal.png',
      department: 'Dept. of CSE, FET-JMI',
      batch: '2020-2024',
      github: 'https://github.com/anzal1',
      linkedin: 'https://www.linkedin.com/in/anzal-husain-abidi-740a40204',
      portfolio: 'https://anzalabidi.netlify.app',
    },
  ],
  guidance_faculty: [
    {
      name: 'Prof. Tanveer Ahmad',
      image: '/images/TanvirAhmad.jpg',
      department: 'Dept. of CSE, FET-JMI',
      portfolio: '',
    },
    {
      name: 'Prof. Sarfaraz Masood',
      image: '/images/SarfarazMassod.png',
      department: 'Dept. of CSE, FET-JMI',
      portfolio: '',
    },
  ],
};
